language: python
python: 3.6

jobs:
  include:
    - stage: Build and deploy to GitHub Pages
      script: mkdocs build --clean --strict
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: site
        on:
          branch: master
