site_name: Go-Caelum Technical Documentation
site_description: The most efficient platform for token economy

theme:
  name: 'material'
  custom_dir: material_override
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - mdx_math:
      enable_dollar_delimiter: True
  - markdown.extensions.extra
  - markdown.extensions.toc:
      permalink: True
  - codehilite:
      guess_lang: false

extra_javascript:
    - js/MathJax.js?config=TeX-AMS_HTML

extra_css:
    - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css
    - css/style.css

extra:
    disqus:
    social:
        - type: 'github'
          link: 'https://github.com/caelumproject'
        - type: 'twitter'
          link: 'https://twitter.com/caelumtoken'
        - type: 'reddit'
          link: ''
        - type: 'facebook'
          link: ''
        - type: 'telegram'
          link: 'https://t.me/caelumofficial'
        - type: 'medium'
          link: 'https://medium.com/caelumproject'

site_url: https://docs.caelumfoundation.com
repo_url: https://github.com/caelumproject/docs
repo_name: caelumproject/docs
google_analytics: ['UA-124597188-1', 'docs.caelumproject.com']

nav:
    - General:
      - Networks: general/networks.md
      - FAQ: general/faq.md
    - Get started:
      - 1. Connect your wallet: get-started/wallet.md
      - 2. Voting: get-started/voting.md
      - 3. Run a node in testnet: get-started/run-node.md
      - 4. Apply your node: get-started/apply-node.md
    # - TomoChain client:
    #   - Getting started: misc/wip.md
    #   - Contributing: misc/wip.md
    - CaelumMaster:
      - Features: tomomaster/features.md
    #   - Contributing: misc/wip.md
    - CaelumScan:
      - Features: tomoscan/features.md
    #   - Contributing: misc/wip.md
    # - TomoWallet:
    #   - Getting started: misc/wip.md
    #   - Contributing: misc/wip.md
    - Masternode:
    #   - Run a masternode:
      - Requirements: masternode/requirements.md
      - Apollo: masternode/tmn.md
      - Applying: masternode/applying.md
    #   - Contributing: misc/wip.md
    #   - FAQ: misc/wip.md
    - Whitepapers and research:
      - Caelum product whitepaper: wp-and-research/whitepaper.md
      - Tomochain original technical whitepaper: wp-and-research/technical-whitepaper.md
      - Tomochain original sharding design paper: wp-and-research/sharding-paper.md
      - Tomochain original economics paper: wp-and-research/economics-paper.md

copyright: If you wish to improve this site, please <a href="https://github.com/caelumproject/docs/issues/new"><i class="fa fa-github"></i> open an issue</a> or <a href="https://github.com/caelumproject/docs/compare"><i class="fa fa-github"></i> send a pull request</a>.<br>CaelumDocs v0.1.0. - Forked from TomoChain Project 2018.
